import './globals.css'
// import ParticleBackground from "./ParticleBackground";


import dynamic from 'next/dynamic';

const DynamicParticleBackground = dynamic(() => import('./ParticleBackground'), {
  ssr: false,
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      {children}

      <div className="backgroundImage"></div>
      {/* <ParticleBackground /> */}
      <DynamicParticleBackground />
      </body>
    </html>
  )
}
